### ISSUE TITLE
mangles comment write/preview tabs

### ISSUE THREAD

**Issue by nerdCopter** [fabiocchetti/wide-github#10]
![image](https://user-images.githubusercontent.com/56646290/84159626-e4af4580-aa32-11ea-9489-3100546c1494.png)
![image](https://user-images.githubusercontent.com/56646290/84159682-f42e8e80-aa32-11ea-9736-188d47b86802.png)

**Comment by fabiocchetti** [comment]
@nerdCopter Thanks for reporting. It should be fixed with version 2.0.0. Please update the add-on 🙂
