### ISSUE TITLE
New GH feature preview

### ISSUE THREAD

**Issue by ManickaP** [fabiocchetti/wide-github#11]
There's a new GH face-lift (Design Updates) and new repo overview page (Repository Refresh). With both of them, Wide GitHub doesn't work, which is expected.
I expected that these feature will eventually end up as non-optional defaults and it would be nice to have this extension keep working with them.

**Comment by jtagcat** [comment]
The preview is now the default without an opt-out.

**Comment by jtagcat** [comment]
Note: this add-on is incompatible with https://addons.mozilla.org/et/firefox/addon/old-school-github/

**Comment by fabiocchetti** [comment]
@ManickaP Thanks for reporting. The new GitHub design is now supported with version 2.0.0. Please update the add-on 🙂
@jtagcat As of now, Wide GitHub supports GitHub's new design only. Despite prior to this release the incompatibility with Old School GitHub add-on was surely an issue, now it is expected. Thanks for understanding.
