### ISSUE TITLE
Add a link to AMO.

### ISSUE THREAD

**Issue by jtagcat** [fabiocchetti/wide-github#13]
Add a link to [AMO](https://addons.mozilla.org/en-US/firefox/addon/widegithub) in the project URL thing on GH (normally next to the description, at the right side of https://github.com/fabiocchetti/wide-github)

**Comment by fabiocchetti** [comment]
Thank you @jtagcat, much appreciated! 🙂

**Comment by jtagcat** [comment]
(I meant this as well:)
![image](https://user-images.githubusercontent.com/38327267/104136120-308ce900-538c-11eb-9b85-2a2ea40ef80a.png)
(you have a gear icon as a repo member there, where you can shoot the link to as well)

**Comment by fabiocchetti** [comment]
Just did it! Sorry I didn't know it was possible on GitHub. Really cool. Thank you once more!
