### ISSUE TITLE
Limit wideness

### ISSUE THREAD

**Issue by jtagcat** [fabiocchetti/wide-github#15]
Not a feature I need right now, but maybe in the future would be nice.

`Instead of using breakpoints, Wide GitHub now makes the page content always fit your screen width. No matter the display size (Issue #9).`

Per-page, say not on gh/org/repo, or gh/org/repo/issues, or only gh/org/repo/pull etc, allow enabling/disabling/capping the wideness. Pages are different.

**Comment by fabiocchetti** [comment]
Feature implemented in [version 2.1.0](https://github.com/fabiocchetti/wide-github/releases/tag/2.1.0).
