### ISSUE TITLE
Makes PR comment boxes wider than the screen

### ISSUE THREAD

**Issue by deadlydog** [fabiocchetti/wide-github#16]
While doing a Pull Request review, if the file contents are wider than the screen you get a horizontal scrollbar. The problem is that Wide GitHub also makes the comment dialog box wider than the screen, so you need to horizontally scroll in order to click the buttons, which is annoying.

Here's a screenshot of the problem with Wide GitHub enabled:
![image](https://user-images.githubusercontent.com/1187140/109851765-ab9aaf00-7c19-11eb-8121-df6bbfe0e8bf.png)

And with Wide GitHub turned off, you don't need to scroll to click the review buttons:
![image](https://user-images.githubusercontent.com/1187140/109851992-ea306980-7c19-11eb-9a4d-b7008ebee218.png)

It would be great if it just made the comment box be as wide as the screen, or even if it didn't resize the comment box, rather than making it as wide as the file being reviewed.

**Comment by fabiocchetti** [comment]
Hi @deadlydog, good catch. Thanks for reporting.

Fixed in [version 2.1.0](https://github.com/fabiocchetti/wide-github/releases/tag/2.1.0).
