### ISSUE TITLE
Google Chrome support.

### ISSUE THREAD

**Issue by rokejulianlockhart** [fabiocchetti/wide-github#18]

**Comment by fabiocchetti** [comment]
👋 Hi and thanks for your interest.

[A similar extension for Google Chrome already exists](https://chrome.google.com/webstore/detail/wide-github/kaalofacklcidaampbokdplbklpeldpj), so I'm not considering to develop another one at the moment.

**Comment by fabiocchetti** [comment]
Today, two years later, I actually [did publish my extension on the Chrome Web Store](https://chromewebstore.google.com/detail/wide-github/hohnneiphpemlbhmiiipkfjnfhmnobpo)—in case it's still relevant. 🙂

**Comment by RokeJulianLockhart** [comment]
> https://github.com/fabiocchetti/wide-github/issues/18#issuecomment-2917828166

@fabiocchetti, superb! Thank you. Now, it truly is closed as "completed".
