### ISSUE TITLE
Blame is not widened

### ISSUE THREAD

**Issue by jamesgeddes** [fabiocchetti/wide-github#21]
When extention is enabled, GitHub blame does not fill the available space

for example

https://github.com/GeekZoneHQ/web/blame/main/CODEOWNERS

extension disabled

![image](https://github.com/user-attachments/assets/801e682d-8a25-4c48-b468-58f18b643004)

extension enabled

![image](https://github.com/user-attachments/assets/2416146d-57b4-4ef3-879d-d132dcb89699)

**Comment by fabiocchetti** [comment]
Thanks for reporting! [Fixed with 2.3.0](https://github.com/fabiocchetti/wide-github/releases/tag/2.3.0).
