### ISSUE TITLE
Why not fit `max-content`?

### ISSUE THREAD

**Issue by bobobox** [fabiocchetti/wide-github#9]
This add-on is helpful, but on my 34" monitor it still limits width, just at a somewhat wider limit. Why not allow using up all the available space?

We can't fix my colleagues who commit enormous single line SQL statements, but maybe we can fix this ;)

**Comment by fabiocchetti** [comment]
@bobobox Thanks for your suggestion, I agree with you. Version 2.0.0 of Wide GitHub should now support that. Please update the add-on 🙂
